const taxReliefData = [
  {
    id: 'lifestyle',
    icon: '💻',
    group: 'lifestyle',
    groupKey: 'group.lifestyle',
    labelKey: 'relief.lifestyle.label',
    descKey: 'relief.lifestyle.desc',
    annualCap: 2500,
    allowMonthly: true,
  },
  {
    id: 'lifestyle_sports',
    icon: '🏃',
    group: 'lifestyle',
    groupKey: 'group.lifestyle',
    labelKey: 'relief.lifestyle_sports.label',
    descKey: 'relief.lifestyle_sports.desc',
    annualCap: 1000,
    allowMonthly: false,
    badge: 'updated',
  },
  {
    id: 'ev_green',
    icon: '⚡',
    group: 'lifestyle',
    groupKey: 'group.lifestyle',
    labelKey: 'relief.ev_green.label',
    descKey: 'relief.ev_green.desc',
    noteKey: 'relief.ev_green.note',
    annualCap: 2500,
    allowMonthly: false,
  },
  {
    id: 'cctv',
    icon: '📷',
    group: 'lifestyle',
    groupKey: 'group.lifestyle',
    labelKey: 'relief.cctv.label',
    descKey: 'relief.cctv.desc',
    noteKey: 'relief.cctv.note',
    annualCap: 2500,
    allowMonthly: false,
    badge: 'new',
  },
  {
    id: 'tourism',
    icon: '🏖️',
    group: 'lifestyle',
    groupKey: 'group.lifestyle',
    labelKey: 'relief.tourism.label',
    descKey: 'relief.tourism.desc',
    noteKey: 'relief.tourism.note',
    annualCap: 1000,
    allowMonthly: false,
    badge: 'new',
  },
  {
    id: 'medical_insurance',
    icon: '🏥',
    group: 'medical',
    groupKey: 'group.medical',
    labelKey: 'relief.medical_insurance.label',
    descKey: 'relief.medical_insurance.desc',
    annualCap: 4000,
    allowMonthly: true,
  },
  {
    id: 'medical_expenses',
    icon: '🩺',
    group: 'medical',
    groupKey: 'group.medical',
    labelKey: 'relief.medical_expenses.label',
    descKey: 'relief.medical_expenses.desc',
    annualCap: 1000,
    allowMonthly: false,
    badge: 'updated',
  },
  {
    id: 'parents_medical',
    icon: '👴',
    group: 'medical',
    groupKey: 'group.medical',
    labelKey: 'relief.parents_medical.label',
    descKey: 'relief.parents_medical.desc',
    annualCap: 8000,
    allowMonthly: false,
  },
  {
    id: 'life_insurance',
    icon: '🛡️',
    group: 'insurance',
    groupKey: 'group.insurance',
    labelKey: 'relief.life_insurance.label',
    descKey: 'relief.life_insurance.desc',
    annualCap: 3000,
    allowMonthly: true,
  },
  {
    id: 'prs',
    icon: '💰',
    group: 'insurance',
    groupKey: 'group.insurance',
    labelKey: 'relief.prs.label',
    descKey: 'relief.prs.desc',
    annualCap: 3000,
    allowMonthly: false,
  },
  {
    id: 'education_self',
    icon: '📚',
    group: 'education',
    groupKey: 'group.education',
    labelKey: 'relief.education_self.label',
    descKey: 'relief.education_self.desc',
    annualCap: 7000,
    allowMonthly: false,
  },
  {
    id: 'sspn',
    icon: '🎓',
    group: 'education',
    groupKey: 'group.education',
    labelKey: 'relief.sspn.label',
    descKey: 'relief.sspn.desc',
    annualCap: 8000,
    allowMonthly: false,
    badge: 'updated',
  },
  {
    id: 'home_loan',
    icon: '🏠',
    group: 'family',
    groupKey: 'group.family',
    labelKey: 'relief.home_loan.label',
    descKey: 'relief.home_loan.desc',
    noteKey: 'relief.home_loan.note',
    annualCap: 7000,
    allowMonthly: false,
    badge: 'new',
  },
  {
    id: 'childcare',
    icon: '👶',
    group: 'family',
    groupKey: 'group.family',
    labelKey: 'relief.childcare.label',
    descKey: 'relief.childcare.desc',
    annualCap: 3000,
    allowMonthly: true,
    badge: 'updated',
  },
  {
    id: 'breastfeeding',
    icon: '🤱',
    group: 'family',
    groupKey: 'group.family',
    labelKey: 'relief.breastfeeding.label',
    descKey: 'relief.breastfeeding.desc',
    annualCap: 1000,
    allowMonthly: false,
  },
  {
    id: 'zakat',
    icon: '🕌',
    group: 'zakat',
    groupKey: 'group.zakat',
    labelKey: 'relief.zakat.label',
    descKey: 'relief.zakat.desc',
    annualCap: null,
    allowMonthly: false,
    isZakat: true,
  },
  {
    id: 'donations',
    icon: '🤝',
    group: 'zakat',
    groupKey: 'group.zakat',
    labelKey: 'relief.donations.label',
    descKey: 'relief.donations.desc',
    annualCap: null,
    allowMonthly: false,
    isDonation: true,
  },
]

export default taxReliefData
